/* 
 * Copyright (c) 2008-2012, Andy Bierman, All Rights Reserved.
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *

*** Generated by yangdump 2.12-0

  Combined SIL module
  module ietf-i2rs-rib
  revision 2018-12-05
  namespace urn:ietf:params:xml:ns:yang:ietf-i2rs-rib
  organization IETF I2RS (Interface to Routing System) Working Group

 */

#include <libxml/xmlstring.h>

#include "procdefs.h"
#include "agt.h"
#include "agt_cb.h"
#include "agt_rpc.h"
#include "agt_timer.h"
#include "agt_util.h"
#include "dlq.h"
#include "ncx.h"
#include "ncx_feature.h"
#include "ncxmod.h"
#include "ncxtypes.h"
#include "rpc.h"
#include "ses.h"
#include "status.h"
#include "val.h"
#include "val_util.h"
#include "xml_util.h"
#include "ietf-i2rs-rib.h"

#include "com.h"
#include "string.h"

/* module static variables */
static ncx_module_t *ietf_i2rs_rib_mod;
static obj_template_t *route_add_obj;
static obj_template_t *route_delete_obj;

/* put your static variables here */

/********************************************************************
* FUNCTION y_ietf_i2rs_rib_init_static_vars
* 
* initialize module static variables
* 
********************************************************************/
static void y_ietf_i2rs_rib_init_static_vars (void)
{
  ietf_i2rs_rib_mod = NULL;
  route_add_obj = NULL;
  route_delete_obj = NULL;

  /* init your static variables here */

} /* y_ietf_i2rs_rib_init_static_vars */


/********************************************************************
* FUNCTION y_ietf_i2rs_rib_route_add_validate
* 
* RPC validation phase
* All YANG constraints have passed at this point.
* Add description-stmt checks in this function.
* 
* INPUTS:
*     see agt/agt_rpc.h for details
* 
* RETURNS:
*     error status
********************************************************************/
static status_t y_ietf_i2rs_rib_route_add_validate (
  ses_cb_t *scb,
  rpc_msg_t *msg,
  xml_node_t *methnode)
{
  status_t res = NO_ERR;
  val_value_t *errorval = NULL;

  val_value_t *return_failure_detail_val;
  boolean return_failure_detail;
  val_value_t *prefix_val;
  const xmlChar *prefix;
  val_value_t *nexthop_val;
  const xmlChar *nexthop;
  val_value_t *route_preference_val;
  uint32 route_preference;

  return_failure_detail_val = val_find_child(
    msg->rpc_input,
    y_ietf_i2rs_rib_M_ietf_i2rs_rib,
    y_ietf_i2rs_rib_N_return_failure_detail);
  if (return_failure_detail_val != NULL && return_failure_detail_val->res == NO_ERR) {
    return_failure_detail = VAL_BOOL(return_failure_detail_val);
  }

  prefix_val = val_find_child(
    msg->rpc_input,
    y_ietf_i2rs_rib_M_ietf_i2rs_rib,
    y_ietf_i2rs_rib_N_prefix);
  if (prefix_val != NULL && prefix_val->res == NO_ERR) {
    prefix = VAL_STRING(prefix_val);
  }

  nexthop_val = val_find_child(
    msg->rpc_input,
    y_ietf_i2rs_rib_M_ietf_i2rs_rib,
    y_ietf_i2rs_rib_N_nexthop);
  if (nexthop_val != NULL && nexthop_val->res == NO_ERR) {
    nexthop = VAL_STRING(nexthop_val);
  }

  route_preference_val = val_find_child(
    msg->rpc_input,
    y_ietf_i2rs_rib_M_ietf_i2rs_rib,
    y_ietf_i2rs_rib_N_route_preference);
  if (route_preference_val != NULL && route_preference_val->res == NO_ERR) {
    route_preference = VAL_UINT(route_preference_val);
  }

  if (res != NO_ERR) {
    agt_record_error(
      scb,
      &msg->mhdr,
      NCX_LAYER_OPERATION,
      res,
      methnode,
      (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
      errorval,
      (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
      errorval);
  }
  return res;

} /* y_ietf_i2rs_rib_route_add_validate */


/********************************************************************
* FUNCTION y_ietf_i2rs_rib_route_add_invoke
* 
* RPC invocation phase
* All constraints have passed at this point.
* Call device instrumentation code in this function.
* 
* INPUTS:
*     see agt/agt_rpc.h for details
* 
* RETURNS:
*     error status
********************************************************************/
static status_t y_ietf_i2rs_rib_route_add_invoke (
  ses_cb_t *scb,
  rpc_msg_t *msg,
  xml_node_t *methnode)
{
  status_t res = NO_ERR;

  val_value_t *return_failure_detail_val;
  boolean return_failure_detail;
  val_value_t *prefix_val;
  xmlChar *prefix;
  xmlChar *address;
  xmlChar *prefixlen;
  val_value_t *nexthop_val;
  xmlChar *nexthop;
  val_value_t *route_preference_val;
  uint32 route_preference = 0;

  return_failure_detail_val = val_find_child(
    msg->rpc_input,
    y_ietf_i2rs_rib_M_ietf_i2rs_rib,
    y_ietf_i2rs_rib_N_return_failure_detail);
  if (return_failure_detail_val != NULL && return_failure_detail_val->res == NO_ERR) {
    return_failure_detail = VAL_BOOL(return_failure_detail_val);
  }

  prefix_val = val_find_child(
    msg->rpc_input,
    y_ietf_i2rs_rib_M_ietf_i2rs_rib,
    y_ietf_i2rs_rib_N_prefix);
  if (prefix_val != NULL && prefix_val->res == NO_ERR) {
    prefix = VAL_STRING(prefix_val);
    address = strsep(&prefix, "/");
    prefixlen = strsep(&prefix, "/");
  }

  nexthop_val = val_find_child(
    msg->rpc_input,
    y_ietf_i2rs_rib_M_ietf_i2rs_rib,
    y_ietf_i2rs_rib_N_nexthop);
  if (nexthop_val != NULL && nexthop_val->res == NO_ERR) {
    nexthop = VAL_STRING(nexthop_val);
  }

  route_preference_val = val_find_child(
    msg->rpc_input,
    y_ietf_i2rs_rib_M_ietf_i2rs_rib,
    y_ietf_i2rs_rib_N_route_preference);
  if (route_preference_val != NULL && route_preference_val->res == NO_ERR) {
    route_preference = VAL_UINT(route_preference_val);
  }

  /* remove the next line if scb is used */
  (void)scb;

  /* remove the next line if methnode is used */
  (void)methnode;

  /* invoke your device instrumentation code here */
  if (address != NULL && prefixlen != NULL && nexthop != NULL && route_preference != 0){
            makeCommand(ZEBRA_IPV4_ROUTE_ADD, address, strtol(prefixlen,(char **)NULL,10), nexthop, route_preference);
    }

  
  return res;

} /* y_ietf_i2rs_rib_route_add_invoke */


/********************************************************************
* FUNCTION y_ietf_i2rs_rib_route_delete_validate
* 
* RPC validation phase
* All YANG constraints have passed at this point.
* Add description-stmt checks in this function.
* 
* INPUTS:
*     see agt/agt_rpc.h for details
* 
* RETURNS:
*     error status
********************************************************************/
static status_t y_ietf_i2rs_rib_route_delete_validate (
  ses_cb_t *scb,
  rpc_msg_t *msg,
  xml_node_t *methnode)
{
  status_t res = NO_ERR;
  val_value_t *errorval = NULL;

  val_value_t *return_failure_detail_val;
  boolean return_failure_detail;
  val_value_t *prefix_val;
  const xmlChar *prefix;
  val_value_t *nexthop_val;
  const xmlChar *nexthop;
  val_value_t *route_preference_val;
  uint32 route_preference;

  return_failure_detail_val = val_find_child(
    msg->rpc_input,
    y_ietf_i2rs_rib_M_ietf_i2rs_rib,
    y_ietf_i2rs_rib_N_return_failure_detail);
  if (return_failure_detail_val != NULL && return_failure_detail_val->res == NO_ERR) {
    return_failure_detail = VAL_BOOL(return_failure_detail_val);
  }

  prefix_val = val_find_child(
    msg->rpc_input,
    y_ietf_i2rs_rib_M_ietf_i2rs_rib,
    y_ietf_i2rs_rib_N_prefix);
  if (prefix_val != NULL && prefix_val->res == NO_ERR) {
    prefix = VAL_STRING(prefix_val);
  }

  nexthop_val = val_find_child(
    msg->rpc_input,
    y_ietf_i2rs_rib_M_ietf_i2rs_rib,
    y_ietf_i2rs_rib_N_nexthop);
  if (nexthop_val != NULL && nexthop_val->res == NO_ERR) {
    nexthop = VAL_STRING(nexthop_val);
  }

  route_preference_val = val_find_child(
    msg->rpc_input,
    y_ietf_i2rs_rib_M_ietf_i2rs_rib,
    y_ietf_i2rs_rib_N_route_preference);
  if (route_preference_val != NULL && route_preference_val->res == NO_ERR) {
    route_preference = VAL_UINT(route_preference_val);
  }

  if (res != NO_ERR) {
    agt_record_error(
      scb,
      &msg->mhdr,
      NCX_LAYER_OPERATION,
      res,
      methnode,
      (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
      errorval,
      (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
      errorval);
  }
  return res;

} /* y_ietf_i2rs_rib_route_delete_validate */


/********************************************************************
* FUNCTION y_ietf_i2rs_rib_route_delete_invoke
* 
* RPC invocation phase
* All constraints have passed at this point.
* Call device instrumentation code in this function.
* 
* INPUTS:
*     see agt/agt_rpc.h for details
* 
* RETURNS:
*     error status
********************************************************************/
static status_t y_ietf_i2rs_rib_route_delete_invoke (
  ses_cb_t *scb,
  rpc_msg_t *msg,
  xml_node_t *methnode)
{
  status_t res = NO_ERR;

  val_value_t *return_failure_detail_val;
  boolean return_failure_detail;
  val_value_t *prefix_val;
  xmlChar *address;
  xmlChar *prefixlen;
  xmlChar *prefix;
  val_value_t *nexthop_val;
  xmlChar *nexthop;
  val_value_t *route_preference_val;
  uint32 route_preference = 0;

  return_failure_detail_val = val_find_child(
    msg->rpc_input,
    y_ietf_i2rs_rib_M_ietf_i2rs_rib,
    y_ietf_i2rs_rib_N_return_failure_detail);
  if (return_failure_detail_val != NULL && return_failure_detail_val->res == NO_ERR) {
    return_failure_detail = VAL_BOOL(return_failure_detail_val);
  }

  prefix_val = val_find_child(
    msg->rpc_input,
    y_ietf_i2rs_rib_M_ietf_i2rs_rib,
    y_ietf_i2rs_rib_N_prefix);
  if (prefix_val != NULL && prefix_val->res == NO_ERR) {
    prefix = VAL_STRING(prefix_val);
    address = strsep(&prefix, "/");
    prefixlen = strsep(&prefix, "/");
  }

  nexthop_val = val_find_child(
    msg->rpc_input,
    y_ietf_i2rs_rib_M_ietf_i2rs_rib,
    y_ietf_i2rs_rib_N_nexthop);
  if (nexthop_val != NULL && nexthop_val->res == NO_ERR) {
    nexthop = VAL_STRING(nexthop_val);
  }

  route_preference_val = val_find_child(
    msg->rpc_input,
    y_ietf_i2rs_rib_M_ietf_i2rs_rib,
    y_ietf_i2rs_rib_N_route_preference);
  if (route_preference_val != NULL && route_preference_val->res == NO_ERR) {
    route_preference = VAL_UINT(route_preference_val);
  }

  /* remove the next line if scb is used */
  (void)scb;

  /* remove the next line if methnode is used */
  (void)methnode;

  /* invoke your device instrumentation code here */
 //if (address != NULL && prefixlen != NULL && nexthop != NULL && route_preference != 0){
              makeCommand(ZEBRA_IPV4_ROUTE_DELETE, address, strtol(prefixlen,(char **)NULL,10), nexthop, route_preference);
//}
  
  return res;

} /* y_ietf_i2rs_rib_route_delete_invoke */

/********************************************************************
* FUNCTION y_ietf_i2rs_rib_init
* 
* initialize the ietf-i2rs-rib server instrumentation library
* 
* INPUTS:
*    modname == requested module name
*    revision == requested version (NULL for any)
* 
* RETURNS:
*     error status
********************************************************************/
status_t y_ietf_i2rs_rib_init (
  const xmlChar *modname,
  const xmlChar *revision)
{
  status_t res = NO_ERR;
  agt_profile_t *agt_profile = agt_get_profile();

  y_ietf_i2rs_rib_init_static_vars();

  /* change if custom handling done */
  if (xml_strcmp(modname, y_ietf_i2rs_rib_M_ietf_i2rs_rib)) {
    return ERR_NCX_UNKNOWN_MODULE;
  }

  if (revision && xml_strcmp(revision, y_ietf_i2rs_rib_R_ietf_i2rs_rib)) {
    return ERR_NCX_WRONG_VERSION;
  }
  res = ncxmod_load_module(
    y_ietf_i2rs_rib_M_ietf_i2rs_rib,
    y_ietf_i2rs_rib_R_ietf_i2rs_rib,
    &agt_profile->agt_savedevQ,
    &ietf_i2rs_rib_mod);
  if (res != NO_ERR) {
    return res;
  }

  route_add_obj = ncx_find_object(
    ietf_i2rs_rib_mod,
    y_ietf_i2rs_rib_N_route_add);
  if (ietf_i2rs_rib_mod == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }
  route_delete_obj = ncx_find_object(
    ietf_i2rs_rib_mod,
    y_ietf_i2rs_rib_N_route_delete);
  if (ietf_i2rs_rib_mod == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }
  res = agt_rpc_register_method(
    y_ietf_i2rs_rib_M_ietf_i2rs_rib,
    y_ietf_i2rs_rib_N_route_add,
    AGT_RPC_PH_VALIDATE,
    y_ietf_i2rs_rib_route_add_validate);
  if (res != NO_ERR) {
    return res;
  }

  res = agt_rpc_register_method(
    y_ietf_i2rs_rib_M_ietf_i2rs_rib,
    y_ietf_i2rs_rib_N_route_add,
    AGT_RPC_PH_INVOKE,
    y_ietf_i2rs_rib_route_add_invoke);
  if (res != NO_ERR) {
    return res;
  }

  res = agt_rpc_register_method(
    y_ietf_i2rs_rib_M_ietf_i2rs_rib,
    y_ietf_i2rs_rib_N_route_delete,
    AGT_RPC_PH_VALIDATE,
    y_ietf_i2rs_rib_route_delete_validate);
  if (res != NO_ERR) {
    return res;
  }

  res = agt_rpc_register_method(
    y_ietf_i2rs_rib_M_ietf_i2rs_rib,
    y_ietf_i2rs_rib_N_route_delete,
    AGT_RPC_PH_INVOKE,
    y_ietf_i2rs_rib_route_delete_invoke);
  if (res != NO_ERR) {
    return res;
  }

  /* put your module initialization code here */
  
  return res;
} /* y_ietf_i2rs_rib_init */

/********************************************************************
* FUNCTION y_ietf_i2rs_rib_init2
* 
* SIL init phase 2: non-config data structures
* Called after running config is loaded
* 
* RETURNS:
*     error status
********************************************************************/
status_t y_ietf_i2rs_rib_init2 (void)
{
  status_t res = NO_ERR;

  /* put your init2 code here */

  return res;
} /* y_ietf_i2rs_rib_init2 */

/********************************************************************
* FUNCTION y_ietf_i2rs_rib_cleanup
*    cleanup the server instrumentation library
* 
********************************************************************/
void y_ietf_i2rs_rib_cleanup (void)
{
  
  agt_rpc_unregister_method(
    y_ietf_i2rs_rib_M_ietf_i2rs_rib,
    y_ietf_i2rs_rib_N_route_add);
  
  agt_rpc_unregister_method(
    y_ietf_i2rs_rib_M_ietf_i2rs_rib,
    y_ietf_i2rs_rib_N_route_delete);
  /* put your cleanup code here */
  
} /* y_ietf_i2rs_rib_cleanup */

/* END ietf_i2rs_rib.c */

